### ISSUE TITLE
Link Twitter

### ISSUE THREAD

**Issue by ctulio** [Kamilahsantos/Kamilahsantos#1]
O Twitter informa que o nick : [@kamilah_santos](https://twitter.com/kamilah_santos) não existe.

**Comment by Kamilahsantos** [comment]
Ajustei com o novo nome de usuário, obrigada =)

**Comment by ctulio** [comment]
A polícia do TOC disse que falta mais um ajuste:grin::
![image](https://user-images.githubusercontent.com/8347597/226469138-7d884c57-4a67-4467-b7ff-2935b730389f.png)
